import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Brain, FileText, Languages, Layers3, BarChart3, Sparkles, ArrowRight, Wand2 } from "lucide-react";

export const Route = createFileRoute("/")({ component: Index });

function Index() {
  return (
    <div className="mx-auto max-w-7xl px-6">
      {/* Hero */}
      <section className="relative pt-20 pb-24 md:pt-28 md:pb-32">
        <div className="mx-auto max-w-3xl text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-border/60 bg-muted/40 px-3 py-1 text-xs font-medium text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-accent" /> AI · ML · NLP Major Project
          </span>
          <h1 className="mt-6 font-display text-5xl font-semibold leading-[1.05] tracking-tight md:text-7xl">
            Question papers, <br />
            <span className="text-gradient">generated by NLP.</span>
          </h1>
          <p className="mt-6 text-lg text-muted-foreground md:text-xl">
            Upload syllabus, notes, or any text. QGen.AI extracts key concepts and produces
            MCQs, fill‑in‑the‑blanks, and descriptive questions — graded by Bloom's taxonomy,
            translated to your language, and adapted to total marks.
          </p>
          <div className="mt-9 flex flex-wrap items-center justify-center gap-3">
            <Link to="/generate">
              <Button size="lg" className="gap-2 bg-gradient-primary text-primary-foreground shadow-glow hover:opacity-95">
                <Wand2 className="h-5 w-5" /> Start generating <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link to="/analytics">
              <Button size="lg" variant="outline" className="gap-2">
                <BarChart3 className="h-5 w-5" /> View analytics
              </Button>
            </Link>
          </div>
        </div>

        {/* glow orb */}
        <div aria-hidden className="pointer-events-none absolute left-1/2 top-1/2 -z-10 h-[500px] w-[500px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/20 blur-[120px]" />
      </section>

      {/* Features */}
      <section className="grid gap-5 pb-24 md:grid-cols-2 lg:grid-cols-4">
        {[
          { icon: Layers3, title: "Bloom's Taxonomy", desc: "All 6 levels — Remember to Create. Pick any mix per paper." },
          { icon: Languages, title: "Multilingual", desc: "English, Hindi, Tamil, Telugu, Marathi out of the box." },
          { icon: Brain, title: "Adaptive Difficulty", desc: "Easy/Medium/Hard split auto-tunes to total marks." },
          { icon: BarChart3, title: "Analytics", desc: "Track Bloom coverage, type mix, difficulty across papers." },
        ].map((f) => (
          <div key={f.title} className="rounded-2xl bg-gradient-card p-6 shadow-card transition-transform hover:-translate-y-1">
            <div className="grid h-11 w-11 place-items-center rounded-xl bg-primary/15 text-primary">
              <f.icon className="h-5 w-5" />
            </div>
            <h3 className="mt-4 text-lg font-semibold">{f.title}</h3>
            <p className="mt-1 text-sm text-muted-foreground">{f.desc}</p>
          </div>
        ))}
      </section>

      {/* Tech stack strip */}
      <section className="mb-24 rounded-2xl border border-border/60 bg-muted/20 p-8">
        <h2 className="text-2xl font-semibold">Powered by modern NLP</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          Frontend in React + Tailwind. Connect any FastAPI backend running HuggingFace Transformers
          (T5/BART), KeyBERT, Sentence Transformers, SpaCy, MongoDB.
        </p>
        <div className="mt-5 flex flex-wrap gap-2">
          {["FastAPI", "HuggingFace", "T5 / BART", "KeyBERT", "Sentence Transformers", "SpaCy", "MongoDB", "React", "TailwindCSS"].map((t) => (
            <span key={t} className="rounded-md border border-border/60 bg-background/60 px-2.5 py-1 font-mono text-xs text-muted-foreground">
              {t}
            </span>
          ))}
        </div>
      </section>
    </div>
  );
}
